name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull binhthien286/cicddemo:latest
      - name: Delete old docker container
        run: sudo docker rm -f cicd-demo-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name cicd-demo-container binhthien286/cicddemo
